"""
fix_fixtures.py
---------------
Reads worldcup.json (good source-of-truth) and the current DB fixtures
supplied as a JSON file argument.

Generates fix_fixtures.sql that updates ONLY:
  ground, date, time, "kickoffUTC"

Does NOT touch: matchId, team1, team2, apiFixtureId, round, stage, group.

Usage:
  python fix_fixtures.py db_rows.json
  
  db_rows.json = paste the Supabase fixtures table JSON array and save it.

Output: fix_fixtures.sql (run this in Supabase SQL Editor)
"""

import json
import re
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path

WC_JSON_PATH = Path(__file__).parent / "docs/2026/worldcup.json"
OUTPUT_SQL   = Path(__file__).parent / "fix_fixtures.sql"

ALIASES = {
    "south korea": "south korea",
    "korea republic": "south korea",
    "czechia": "czech republic",
    "czech republic": "czech republic",
    "turkiye": "turkey",
    "turkey": "turkey",
    "cote d'ivoire": "ivory coast",
    "ivory coast": "ivory coast",
    "dr congo": "dr congo",
    "congo dr": "dr congo",
    "bosnia and herzegovina": "bosnia & herzegovina",
    "bosnia & herzegovina": "bosnia & herzegovina",
    "cabo verde": "cape verde",
    "cape verde": "cape verde",
    "ir iran": "iran",
    "iran": "iran",
}

def norm(name):
    n = name.lower().strip().replace("\u00e7", "c").replace("\u00fc", "u")
    return ALIASES.get(n, n)

def parse_utc_offset(time_str):
    m = re.search(r"UTC([+-]\d+(?:\.\d+)?)", time_str)
    return int(float(m.group(1)) * 60) if m else 0

def time_str_to_utc(date_str, time_str):
    try:
        hm = re.match(r"(\d{1,2}):(\d{2})", time_str)
        if not hm:
            return None
        hour, minute = int(hm.group(1)), int(hm.group(2))
        offset_min = parse_utc_offset(time_str)
        local_dt = datetime(
            *[int(p) for p in date_str.split("-")],
            hour, minute, tzinfo=timezone(timedelta(minutes=offset_min))
        )
        return local_dt.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S+00:00")
    except Exception as e:
        print(f"  WARNING: Could not parse '{time_str}' on '{date_str}': {e}")
        return None

def esc(s):
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"

def main():
    wc_data = json.loads(WC_JSON_PATH.read_text(encoding="utf-8"))
    wc_by_teams = {}
    wc_by_num = {}
    for m in wc_data["matches"]:
        key = (norm(m.get("team1","")), norm(m.get("team2","")))
        wc_by_teams[key] = m
        if "num" in m:
            wc_by_num[int(m["num"])] = m

    if len(sys.argv) < 2:
        print("Usage: python fix_fixtures.py db_rows.json")
        print("  Export your fixtures table from Supabase as JSON and pass it here.")
        sys.exit(1)

    db_rows = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
    print(f"Loaded {len(db_rows)} DB rows from {sys.argv[1]}")

    sql_lines = [
        "-- Generated by fix_fixtures.py",
        "-- Updates: ground, date, time, \"kickoffUTC\"",
        "-- Does NOT change: matchId, team1, team2, apiFixtureId\n",
    ]

    matched = skipped = 0
    for row in db_rows:
        mid     = row.get("matchId")
        t1      = row.get("team1", "")
        t2      = row.get("team2", "")
        api_id  = row.get("apiFixtureId")

        wc = None
        if api_id is not None:
            wc = wc_by_num.get(int(api_id))
        if wc is None:
            wc = wc_by_teams.get((norm(t1), norm(t2)))

        if wc is None:
            print(f"  SKIP  matchId={mid!r}  '{t1}' vs '{t2}'  apiId={api_id}")
            skipped += 1
            continue

        gd = wc.get("date")
        gt = wc.get("time")
        gg = wc.get("ground")
        gu = time_str_to_utc(gd, gt) if gd and gt else None

        sql_lines.append(
            f"UPDATE fixtures\n"
            f"  SET ground = {esc(gg)},\n"
            f"      date   = {esc(gd)},\n"
            f"      time   = {esc(gt)},\n"
            f"      \"kickoffUTC\" = {esc(gu) if gu else 'NULL'}::timestamptz\n"
            f"  WHERE \"matchId\" = {esc(mid)};\n"
        )
        matched += 1

    OUTPUT_SQL.write_text("\n".join(sql_lines), encoding="utf-8")
    print(f"\n  {matched} rows matched, {skipped} skipped")
    print(f"  SQL written to: {OUTPUT_SQL}")

if __name__ == "__main__":
    main()
